name: "ModernTags"
main: "com.github.groundbreakingmc.moderntags.ModernTags"
version: "1.0.0"
api-version: "1.20"
folia-supported: true

author: "GroundbreakingMC"
website: "https://github.com/groundbreakingmc"

depend: [ "packetevents" ]
softdepend: [ "PlaceholderAPI", "Vault" ]
libraries: [ "org.spongepowered:configurate-yaml:4.2.0" ]

commands:
  moderntags:
    description: "ModernTags reload command"
    permission: moderntags.reload

permissions:
  moderntags.reload:
    description: "Allows to reload the plugin"
    default: op

  moderntags.see.own:
    description: "Allows to see own tag"
    default: false

  moderntags.see.other:
    description: "Allows to see other player tags"
    default: true
